# Generated by Django 4.2.2 on 2023-07-04 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=12)),
                ('operator_code', models.CharField(max_length=5)),
                ('tag', models.CharField(max_length=255)),
                ('time_zone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_start', models.DateTimeField()),
                ('text_message', models.TextField()),
                ('client_filter', models.CharField(max_length=255)),
                ('datetime_end', models.DateTimeField()),
                ('is_finish', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('send_status', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sender.client')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sender.mailing')),
            ],
        ),
    ]
