# Generated by Django 4.2.2 on 2023-07-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='is_finish',
            field=models.BooleanField(default=False),
        ),
    ]
